version: '3'
services:
  postgresql:
    container_name: postgresql
    image: postgres:13.5
    restart: unless-stopped
    env_file:
      - "./.env"
    ports:
      - "5432:5432"
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    networks:
      - app

  api_service:
    container_name: api_service
    build: 
      context: ./rates
    image: api_service
    env_file:
      - "./.env"
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - postgresql
    networks:
      - app

networks:
  app:
